import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProviders } from "./components/ReduxProvider";
import AuthGuard from "./components/AuthGuard";
import { AuthProvider } from "../context/AuthContext";
import ConditionalLayout from "./components/ConditionalLayout";
// import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ubook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal?: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProviders>
          <AuthGuard requireAuth={true}>
            <AuthProvider>
              <ConditionalLayout>
                {/* <ThemeProvider
                  attribute="class"
                  defaultTheme="dark"
                  enableSystem
                  disableTransitionOnChange
                > */}
                {children}
                {modal}
                {/* <Toaster
                  position="bottom-right"
                  toastOptions={{
                    duration: 4000,
                    style: {
                      background: "#1a1a1a",
                      color: "#fff",
                      borderRadius: "10px",
                    },
                  }}
                /> */}
                <Toaster
                  theme="dark"
                  position="bottom-right"
                  toastOptions={{
                    duration: 4000,
                  }}
                />
                {/* </ThemeProvider> */}
              </ConditionalLayout>
            </AuthProvider>
          </AuthGuard>
        </ReduxProviders>
      </body>
    </html>
  );
}
