# Generated by Django 5.2.7 on 2026-01-16 09:40

import core.generate
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigIntegerField(default=core.generate.generate_snowflake_id, editable=False, primary_key=True, serialize=False)),
                ('verb', models.CharField(choices=[('post', 'New Post'), ('like', 'Liked'), ('comment', 'Commented'), ('follow_request', 'Follow Request'), ('follow_accept', 'Follow Accepted'), ('mention', 'Mentioned'), ('share', 'Shared'), ('reply', 'Replied')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationActor',
            fields=[
                ('id', models.BigIntegerField(default=core.generate.generate_snowflake_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_actions', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='notifications.notification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigIntegerField(default=core.generate.generate_snowflake_id, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('push', 'Push Notification'), ('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App'), ('websocket', 'WebSocket')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Notification Delivery',
                'verbose_name_plural': 'Notification Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTarget',
            fields=[
                ('id', models.BigIntegerField(default=core.generate.generate_snowflake_id, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.BigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='notifications.notification')),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_seen'], name='notificatio_recipie_6c54a8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'verb'], name='notificatio_recipie_020cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationactor',
            index=models.Index(fields=['notification', 'actor'], name='notificatio_notific_672cc9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationactor',
            unique_together={('notification', 'actor')},
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['notification', 'channel'], name='notificatio_notific_7707f8_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['status'], name='notificatio_status_533452_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['channel', 'status'], name='notificatio_channel_edd073_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationdelivery',
            unique_together={('notification', 'channel')},
        ),
        migrations.AddIndex(
            model_name='notificationtarget',
            index=models.Index(fields=['notification'], name='notificatio_notific_cd86f9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtarget',
            index=models.Index(fields=['content_type', 'object_id'], name='notificatio_content_4b73e8_idx'),
        ),
    ]
