# Generated by Django 5.2.7 on 2026-01-19 01:23

import core.generate
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigIntegerField(default=core.generate.generate_snowflake_id, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('portal', models.URLField(blank=True, null=True)),
                ('email_domains', models.JSONField(blank=True, default=dict, help_text='Dictionary of email domains associated with the institute', null=True)),
                ('courses', models.JSONField(blank=True, default=dict, help_text='Dictionary of courses offered by the institute', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('logo', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('accreditation', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Dictionary of social media links', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Institute',
                'verbose_name_plural': 'Institutes',
                'db_table': 'institute',
                'ordering': ['-created_at'],
            },
        ),
    ]
