# Generated by Django 5.2.7 on 2026-01-19 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='email_domains',
        ),
        migrations.CreateModel(
            name='InstituteEmailDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('domain_type', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('alumni', 'Alumni'), ('staff', 'Staff')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_domains', to='institutes.institute')),
            ],
            options={
                'unique_together': {('institute', 'domain')},
            },
        ),
    ]
