# Generated by Django 5.2.7 on 2026-01-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0003_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
