import type { Metadata } from "next";
import LayoutsWrapper from "../../components/LayoutsWrapper";

export const metadata: Metadata = {
  title: "Activity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  // modal,
}: Readonly<{
  children: React.ReactNode;
  // modal: React.ReactNode;
}>) {
  return (
    <>
      <LayoutsWrapper>
        {children}
        {/* {modal} */}
      </LayoutsWrapper>
    </>
  );
}
