# Generated by Django 5.2.7 on 2026-01-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('dnd', 'Do Not Disturb')], default='online', help_text="User's current online status", max_length=10),
        ),
    ]
