# Generated by Django 5.2.7 on 2026-01-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_status_manual',
            field=models.BooleanField(default=False, help_text='Whether the status was set manually by the user'),
        ),
    ]
