# Generated by Django 5.2.7 on 2026-01-19 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_status_manual'),
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='institutes.institute'),
        ),
    ]
