# Generated by Django 5.2.7 on 2026-01-19 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_origin'),
        ('institutes', '0002_remove_institute_email_domains_instituteemaildomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='origin',
        ),
        migrations.AddField(
            model_name='user',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='institutes.institute'),
        ),
    ]
