# Generated by Django 5.2.7 on 2026-01-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='edu_mail',
            new_name='professional_email',
        ),
    ]
