# Generated by Django 5.2.7 on 2026-02-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_edu_mail_user_professional_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_email',
            field=models.CharField(choices=[('email', 'Personal Email'), ('professional_email', 'Professional Email')], default='email', help_text='Which email address to use for notifications', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='professional_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('alumni', 'Alumni'), ('other', 'Other')], default=None, max_length=50, null=True),
        ),
    ]
