import type { Metadata } from "next";
import AuthGuard from "../components/AuthGuard";

export const metadata: Metadata = {
  title: "Login • Ubook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <AuthGuard requireAuth={true}>
        <div className="relative min-h-screen w-full overflow-hidden">
          <div
            // className="absolute inset-0 z-0 bg-[url('https://www.bracu.ac.bd/sites/default/files/uploads/2025/07/01/sun_drance.jpg')] bg-cover bg-center blur-md scale-110"
            aria-hidden="true"
          />
          <div className="absolute inset-0 z-0 bg-black/75" />

          <div className="relative z-10 h-full w-full">
            {children}
          </div>
        </div>
      </AuthGuard>
    </>
  );
}
