# Generated by Django 5.2.7 on 2025-12-12 03:14

import core.generate
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigIntegerField(default=core.generate.generate_snowflake_id, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigIntegerField(default=core.generate.generate_snowflake_id, editable=False, primary_key=True, serialize=False)),
                ('invite_type', models.CharField(choices=[('club', 'Club Invitation'), ('event', 'Event Invitation')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigIntegerField(default=core.generate.generate_snowflake_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Role name (e.g., Member, Moderator, Admin)', max_length=50)),
                ('can_manage_members', models.BooleanField(default=False, help_text='Can add/remove members and assign roles')),
                ('can_manage_posts', models.BooleanField(default=False, help_text='Can delete/pin posts')),
                ('can_manage_events', models.BooleanField(default=False, help_text='Can create/edit/delete events')),
                ('can_manage_settings', models.BooleanField(default=False, help_text='Can edit club settings')),
                ('custom_permissions', models.JSONField(blank=True, default=dict, help_text='Additional custom permissions as key-value pairs')),
                ('is_default', models.BooleanField(default=False, help_text='Is this a default role (e.g., Member role for new joiners)')),
                ('color', models.CharField(blank=True, help_text='Hex color code for role display (e.g., #FF5733)', max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-can_manage_settings', '-can_manage_members', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigIntegerField(default=core.generate.generate_snowflake_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(help_text="Origin/location of the club (e.g., 'BRACU', 'International', 'Online')", max_length=50)),
                ('about', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('banner', models.URLField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('closed', 'Closed'), ('secret', 'Secret')], default='public', max_length=20)),
                ('allow_public_posts', models.BooleanField(default=True)),
                ('rules', models.TextField(blank=True, default='', help_text='Club rules and guidelines', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubPost',
            fields=[
                ('id', models.BigIntegerField(default=core.generate.generate_snowflake_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(help_text='The club this post belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='club_posts', to='clubs.club')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
