# Generated by Django 5.2.7 on 2025-12-12 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpost',
            name='post',
            field=models.OneToOneField(blank=True, help_text='The underlying post object containing all content and interactions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_post', to='posts.post'),
        ),
        migrations.AddField(
            model_name='event',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='club_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invite',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='invite',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='clubs.event'),
        ),
        migrations.AddField(
            model_name='invite',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invite',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='clubs', through='clubs.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='membership',
            name='primary_role',
            field=models.ForeignKey(blank=True, help_text='Primary/display role for this membership', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_memberships', to='clubs.role'),
        ),
        migrations.AddField(
            model_name='membership',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text="User's roles in the club", related_name='memberships', to='clubs.role'),
        ),
        migrations.AddIndex(
            model_name='clubpost',
            index=models.Index(fields=['club', '-created_at'], name='clubs_clubp_club_id_1b722a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['club', 'start_time'], name='clubs_event_club_id_8a582a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='clubs_event_status_e20eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='invite',
            index=models.Index(fields=['club', 'status', 'created_at'], name='clubs_invit_club_id_28b058_idx'),
        ),
        migrations.AddIndex(
            model_name='invite',
            index=models.Index(fields=['event', 'status', 'created_at'], name='clubs_invit_event_i_1eeed0_idx'),
        ),
        migrations.AddIndex(
            model_name='invite',
            index=models.Index(fields=['invitee', 'status'], name='clubs_invit_invitee_5e6e68_idx'),
        ),
        migrations.AddIndex(
            model_name='invite',
            index=models.Index(fields=['inviter', 'created_at'], name='clubs_invit_inviter_04b0a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='invite',
            constraint=models.CheckConstraint(condition=models.Q(('event__isnull', True), ('invite_type', 'event'), _negated=True), name='event_invite_must_have_event'),
        ),
        migrations.AddConstraint(
            model_name='invite',
            constraint=models.UniqueConstraint(condition=models.Q(('invite_type', 'club'), ('status', 'pending')), fields=('club', 'invitee'), name='unique_pending_club_invite'),
        ),
        migrations.AddConstraint(
            model_name='invite',
            constraint=models.UniqueConstraint(condition=models.Q(('invite_type', 'event'), ('status', 'pending')), fields=('event', 'invitee'), name='unique_pending_event_invite'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['name'], name='clubs_club_name_657a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['slug'], name='clubs_club_slug_9373ca_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['name', 'origin'], name='clubs_club_name_2be4ee_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['privacy', 'is_active'], name='clubs_club_privacy_6d416f_idx'),
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.UniqueConstraint(fields=('name', 'origin'), name='unique_name_origin_per_club'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['club', 'name'], name='clubs_role_club_id_7513de_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['club', 'is_default'], name='clubs_role_club_id_fb22e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('name__isnull', False)), fields=('club', 'name'), name='unique_role_name_per_club'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'club'], name='clubs_membe_user_id_94a212_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'club')},
        ),
    ]
