# Generated by Django 5.2.7 on 2025-12-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
