# Generated by Django 5.2.7 on 2025-12-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_invite_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_events',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_members',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_posts',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_settings',
        ),
        migrations.RemoveField(
            model_name='role',
            name='custom_permissions',
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text="Permission dictionary with keys like 'can_manage_members', 'can_manage_posts', etc."),
        ),
    ]
