# Generated by Django 5.2.7 on 2026-01-19 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_role_options_remove_role_can_manage_events_and_more'),
        ('institutes', '0002_remove_institute_email_domains_instituteemaildomain'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='club',
            new_name='clubs_club_name_06c860_idx',
            old_name='clubs_club_name_2be4ee_idx',
        ),
        migrations.AlterField(
            model_name='club',
            name='origin',
            field=models.ForeignKey(help_text='Origin institute of the club', on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='institutes.institute'),
        ),
    ]
