# Generated by Django 5.2.7 on 2026-01-19 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_rename_clubs_club_name_2be4ee_idx_clubs_club_name_06c860_idx_and_more'),
        ('institutes', '0002_remove_institute_email_domains_instituteemaildomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='is_public',
            field=models.BooleanField(default=True, help_text='True if club is open to all institutes'),
        ),
        migrations.AlterField(
            model_name='club',
            name='origin',
            field=models.ForeignKey(blank=True, help_text='Null means local / global / cross-institute club', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='institutes.institute'),
        ),
    ]
