# Generated by Django 5.2.7 on 2026-01-19 02:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_club_is_public_alter_club_origin'),
        ('institutes', '0002_remove_institute_email_domains_instituteemaildomain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='club',
            name='unique_name_origin_per_club',
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.UniqueConstraint(fields=('name', 'origin'), name='unique_club_per_institute'),
        ),
    ]
