# Generated by Django 5.2.7 on 2026-02-15 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_remove_club_unique_name_origin_per_club_and_more'),
        ('institutes', '0004_institute_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='origin',
            field=models.ForeignKey(blank=True, default='Global', help_text='Null means local / global / cross-institute club', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='institutes.institute'),
        ),
    ]
