# Generated by Django 5.2.7 on 2025-12-12 03:14

import apps.posts.models
import core.generate
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigIntegerField(default=core.generate.generate_snowflake_id, editable=False, primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('TEXT', 'Text/Status'), ('IMAGE', 'Image'), ('VIDEO', 'Video/Reel'), ('MIXED', 'Mixed Media')], default='TEXT', max_length=10)),
                ('title', models.CharField(blank=True, help_text='Optional title (commonly used for club posts)', max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to=apps.posts.models.post_image_upload_path)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=apps.posts.models.post_video_upload_path)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False, help_text='For club posts: whether the post is pinned in the club')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(blank=True, help_text='If set, this is a club post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='clubs.club')),
                ('original_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='posts.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigIntegerField(default=core.generate.generate_snowflake_id, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=10)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to=apps.posts.models.post_image_upload_path)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=apps.posts.models.post_video_upload_path)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='posts.post')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='posts_post_author__f8ea20_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['club', '-created_at'], name='posts_post_club_id_bb7523_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type'], name='posts_post_post_ty_83ef6a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_public', '-created_at'], name='posts_post_is_publ_1f976f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_deleted'], name='posts_post_is_dele_876c95_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['club', 'is_pinned', '-created_at'], name='posts_post_club_id_1ab204_idx'),
        ),
        migrations.AddIndex(
            model_name='postmedia',
            index=models.Index(fields=['post', 'order'], name='posts_postm_post_id_857b22_idx'),
        ),
    ]
